### PR TITLE
Making dropdown component reusable

### PR DESCRIPTION
**Pull request by akshara-sun**
fixes for #289 

#### Component Reusability 
- [ ] make Dropdown component in `Dropdown.js` reusable by removing anything that is specific to the the download dropdown.
- [ ] Successful completion of PREVIOUS to-do should result in `LoginDropdown.js` to be deleted.

#### Fixes for Login Dropdown specifically
- [ ] display user's avatar when user is logged in (should use freesound.me() )
- [ ] "Logged in as ____" should display user's first name or username (@hamirmahal @amilajack thoughts on this?)
- [ ] Log Out option in dropdown menu should be functional

### CODE REVIEW

**Comment by hamirmahal** [comment]
> * [ ]  "Logged in as ____" should display user's first name or username (@hamirmahal @amilajack thoughts on this?)

[The response subsection of the user resources section of the Freesound API](https://freesound.org/docs/api/resources_apiv2.html#id33) gives consumers access to a `username` field.

It doesn't look like they provide some method by which consumers can access users' first names, so I think we should have the login dropdown say something like

```
`Hello, ${username}!`
```

**Comment by amilajack** [comment]
@akshara-sun the PR title isn't clear. Can you please clarify the PR title

**Comment by akshara-sun** [comment]
> > * [ ]   "Logged in as ____" should display user's first name or username (@hamirmahal @amilajack thoughts on this?)
> 
> [The response subsection of the user resources section of the Freesound API](https://freesound.org/docs/api/resources_apiv2.html#id33) gives consumers access to a `username` field.
> 
> It doesn't look like they provide some method by which consumers can access users' first names, so I think we should have the login dropdown say something like
> 
> ```
> `Hello, ${username}!`
> ```

@hamirmahal yeah, username is only used for referencing the user that uploaded the sounds but I don't think it can be used for their avatar or the actual name of user. Check [this ](https://amilajack.github.io/freesound-client/classes/freesound.html#me)out tho - It looks like `freesound.me()` might work.

**Comment by akshara-sun** [comment]
@hamirmahal 

@amilajack said that in order to use freesound.me(), we'd have to use `async` and `await `

**Pull request closed without merging**
